apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-gateway
  namespace: default
spec:
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  - mesh
  hosts:
  - api.mattmoor.io
  http:

  - match:
    - uri:
        exact: /sample.SampleService/Unary
    rewrite:
      authority: unary-sampleservice.default.svc.cluster.local
    route:
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100

  - match:
    - uri:
        exact: /sample.SampleService/StreamIn
    rewrite:
      authority: streamin-sampleservice.default.svc.cluster.local
    route:
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100

  - match:
    - uri:
        exact: /sample.SampleService/StreamOut
    rewrite:
      authority: streamout-sampleservice.default.svc.cluster.local
    route:
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100

  - match:
    - uri:
        exact: /sample.SampleService/Stream
    rewrite:
      authority: stream-sampleservice.default.svc.cluster.local
    route:
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100

